### PR TITLE
Add cloudsmith registry

### PR DESCRIPTION
**Pull request by DavidS**

### CODE REVIEW

**Review by antonbabenko — CHANGES_REQUESTED** [review]
As far as I can see, cloudsmith is commercial offering. Please move it to the corresponding section.

**Comment by DavidS** [comment]
> As far as I can see, cloudsmith is commercial offering. Please move it to the corresponding section.

Yes, it is. A commercial "private registry". What section should I put it in then?

**Comment by antonbabenko** [comment]
I think it should be under "Terraform Enterprise" (to be renamed) - https://github.com/shuaibiyy/awesome-tf#terraform-enterprise

**Comment by DavidS** [comment]
What do you think of this version?

**Review by antonbabenko — APPROVED** [review]
LGTM

**Pull request merged**
